### ISSUE TITLE
Add Epoch 3.0 and Bitcoin operations

### ISSUE THREAD

**Issue by igorsyl** [Trust-Machines-Archive/stacks-blockchain#4]
## Code Exploration

- Inspect the implementation for the Bitcoin operation `StacksStx` in the `develop` branch: 
  - https://github.com/Trust-Machines/stacks-blockchain/blob/d64a8305cffb6c3904ec0956b9dc59ba2839fada/src/chainstate/burn/operations/mod.rs#L281
  - Understand the functionality associated with a Bitcoin operation so we can add new ones.

- Inspect the Bitcoin operation implementation for `DelegateStx` in the `next` branch:
  - https://github.com/Trust-Machines/stacks-blockchain/blob/748eff4a8ad01aa63611f530813f1f19fbbb25e5/src/chainstate/burn/operations/mod.rs#L319
  - This operation will be activated with Stacks 2.1 so let's understand how this operation is gated by a new epoch.

- Inspect the new Epoch 2.1 in the `next` branch:
  - https://github.com/Trust-Machines/stacks-blockchain/blob/748eff4a8ad01aa63611f530813f1f19fbbb25e5/stacks-common/src/types/mod.rs#L74

## Code Contributions

- Continue the work in this PR (you can create your own and cherry pick commits too :)
  - https://github.com/Trust-Machines/stacks-blockchain/pull/3

- Add a new Epoch 3.0 and feature gate the new functionality below.

- Disallow stacking operations via the Stacks `pox` contract by making the stacking methods private here:
  - https://github.com/Trust-Machines/stacks-blockchain/blob/748eff4a8ad01aa63611f530813f1f19fbbb25e5/src/chainstate/stacks/boot/pox-2.clar#L583
  - Since we're changing the `pox-2` contract, we need to create a new `pox-3` contract--let's call it `sbtc`.

- Add support for Bitcoin operations for all the stacking operations: delegate aggregation commits, stacking extensions, delegated stacking extensions
  - https://github.com/Trust-Machines/stacks-blockchain/blob/748eff4a8ad01aa63611f530813f1f19fbbb25e5/src/chainstate/stacks/boot/docs.rs#L13

- Add new Bitcoin operations for the Peg Wallet functionality:
  - Note: The operation `LeaderBlockCommit` will change its behavior and Bitcoin serialization format.
  - These are in the PR above:
    - Peg Hand-off Transaction
    - Peg-In Transaction
    - Peg-out Request Transaction 
    - Peg-out Fulfillment Transaction

**Comment by netrome** [comment]
This is done upstream and tracked in https://github.com/orgs/Trust-Machines/projects/5/views/4
